import { useState, useEffect } from "react";

const PAIRS = [
  { symbol: "BTC/USDT", price: 97500.0, change: 2.58 },
  { symbol: "ETH/USDT", price: 3450.45, change: -2.41 },
  { symbol: "XRP/USDT", price: 2.35, change: 5.38 },
  { symbol: "BNB/USDT", price: 680.0, change: 2.29 },
  { symbol: "SOL/USDT", price: 185.75, change: 4.65 },
  { symbol: "DOGE/USDT", price: 0.32, change: 6.67 },
  { symbol: "ADA/USDT", price: 0.95, change: -4.04 },
  { symbol: "TRX/USDT", price: 0.24, change: 4.35 },
  { symbol: "AVAX/USDT", price: 42.2, change: -4.74 },
  { symbol: "LINK/USDT", price: 24.0, change: 5.49 },
  { symbol: "SHIB/USDT", price: 0.000024, change: 4.76 },
  { symbol: "SUI/USDT", price: 4.2, change: 8.25 },
  { symbol: "XLM/USDT", price: 0.42, change: 5.0 },
  { symbol: "DOT/USDT", price: 7.5, change: 4.9 },
  { symbol: "HBAR/USDT", price: 0.28, change: 7.69 },
  { symbol: "BCH/USDT", price: 485.0, change: 2.65 },
  { symbol: "UNI/USDT", price: 14.5, change: 4.92 },
  { symbol: "LTC/USDT", price: 108.0, change: -2.88 },
  { symbol: "PEPE/USDT", price: 0.000018, change: 11.76 },
  { symbol: "NEAR/USDT", price: 5.2, change: 5.69 },
  { symbol: "ICP/USDT", price: 11.5, change: 4.74 },
  { symbol: "FET/USDT", price: 2.1, change: 9.38 },
  { symbol: "MATIC/USDT", price: 0.52, change: 4.0 },
  { symbol: "RNDR/USDT", price: 8.5, change: 8.28 },
  { symbol: "ARB/USDT", price: 1.1, change: 4.76 },
  { symbol: "ATOM/USDT", price: 9.8, change: 3.9 },
  { symbol: "SEI/USDT", price: 0.48, change: 9.09 },
  { symbol: "RUNE/USDT", price: 5.5, change: 6.8 },
  { symbol: "MKR/USDT", price: 1850.0, change: 4.82 },
  { symbol: "QNT/USDT", price: 118.0, change: 4.89 },
  { symbol: "LDO/USDT", price: 1.9, change: 4.97 },
  { symbol: "GALA/USDT", price: 0.04, change: 7.69 },
  { symbol: "JASMY/USDT", price: 0.03, change: 6.67 },
  { symbol: "SAND/USDT", price: 0.58, change: 5.45 },
  { symbol: "FLOW/USDT", price: 0.85, change: 4.6 },
  { symbol: "MANA/USDT", price: 0.39, change: 3.75 },
  { symbol: "AXS/USDT", price: 6.2, change: 5.1 },
  { symbol: "APE/USDT", price: 1.15, change: 4.3 },
  { symbol: "OP/USDT", price: 1.8, change: 6.2 },
  { symbol: "INJ/USDT", price: 22.5, change: 7.45 },
  { symbol: "GRT/USDT", price: 0.21, change: 3.9 },
  { symbol: "AAVE/USDT", price: 185.0, change: 5.6 },
  { symbol: "SNX/USDT", price: 2.8, change: 4.15 },
  { symbol: "CRV/USDT", price: 0.55, change: 3.5 },
  { symbol: "ENS/USDT", price: 26.0, change: 6.8 },
  { symbol: "BLUR/USDT", price: 0.28, change: 5.9 },
  { symbol: "IMX/USDT", price: 1.45, change: 4.75 },
  { symbol: "CAKE/USDT", price: 2.2, change: 3.2 },
  { symbol: "COMP/USDT", price: 55.0, change: 4.4 },
  { symbol: "YFI/USDT", price: 6500.0, change: 2.85 },
  { symbol: "BAL/USDT", price: 3.5, change: 3.6 },
  { symbol: "ZRX/USDT", price: 0.42, change: 2.95 },
  { symbol: "CHZ/USDT", price: 0.085, change: 5.3 },
  { symbol: "ENJ/USDT", price: 0.19, change: 4.1 },
  { symbol: "BAT/USDT", price: 0.22, change: 3.4 },
  { symbol: "ZIL/USDT", price: 0.022, change: 4.8 },
  { symbol: "ONE/USDT", price: 0.018, change: 3.7 },
  { symbol: "KAVA/USDT", price: 0.68, change: 4.2 },
  { symbol: "ALGO/USDT", price: 0.17, change: 3.55 },
  { symbol: "VET/USDT", price: 0.038, change: 4.9 },
  { symbol: "THETA/USDT", price: 1.45, change: 5.2 },
  { symbol: "FIL/USDT", price: 4.8, change: 4.65 },
  { symbol: "EOS/USDT", price: 0.75, change: 3.8 },
  { symbol: "XTZ/USDT", price: 0.72, change: 3.1 },
  { symbol: "IOTA/USDT", price: 0.22, change: 4.3 },
  { symbol: "NEO/USDT", price: 11.5, change: 3.95 },
  { symbol: "WAVES/USDT", price: 1.85, change: 4.5 },
  { symbol: "DASH/USDT", price: 28.0, change: 2.75 },
  { symbol: "XMR/USDT", price: 165.0, change: -1.2 },
  { symbol: "ZEC/USDT", price: 28.5, change: -0.85 },
  { symbol: "EGLD/USDT", price: 32.0, change: 4.1 },
  { symbol: "ROSE/USDT", price: 0.078, change: 5.6 },
  { symbol: "KSM/USDT", price: 25.0, change: 3.7 },
  { symbol: "CELO/USDT", price: 0.85, change: 4.25 },
  { symbol: "ANKR/USDT", price: 0.038, change: 5.1 },
  { symbol: "SKL/USDT", price: 0.068, change: 4.4 },
  { symbol: "STORJ/USDT", price: 0.42, change: 4.8 },
  { symbol: "BAND/USDT", price: 1.25, change: 4.2 },
  { symbol: "WLD/USDT", price: 2.3, change: 6.4 },
  { symbol: "STX/USDT", price: 1.75, change: 5.8 },
  { symbol: "CFX/USDT", price: 0.165, change: 4.3 },
  { symbol: "MAGIC/USDT", price: 0.85, change: 5.2 },
  { symbol: "TIA/USDT", price: 3.8, change: 7.1 },
  { symbol: "PYTH/USDT", price: 0.32, change: 6.5 },
  { symbol: "JTO/USDT", price: 2.1, change: 5.9 },
  { symbol: "JUP/USDT", price: 0.55, change: 6.2 },
  { symbol: "WIF/USDT", price: 1.45, change: 8.9 },
  { symbol: "BOME/USDT", price: 0.0085, change: 9.5 },
  { symbol: "NOT/USDT", price: 0.0062, change: 7.3 },
  { symbol: "IO/USDT", price: 3.4, change: 6.1 },
  { symbol: "ZK/USDT", price: 0.12, change: 5.8 },
  { symbol: "LISTA/USDT", price: 0.45, change: 6.9 },
  { symbol: "EIGEN/USDT", price: 2.8, change: 7.2 },
  { symbol: "HMSTR/USDT", price: 0.0035, change: 8.1 },
  { symbol: "CATI/USDT", price: 0.18, change: 7.5 },
  { symbol: "DOGS/USDT", price: 0.0005, change: 6.8 },
  { symbol: "MAJOR/USDT", price: 0.042, change: 8.4 },
  { symbol: "NEIRO/USDT", price: 0.0008, change: 12.3 },
];

export function useTicker() {
  const [pairs, setPairs] = useState(PAIRS);
  useEffect(() => {
    const interval = setInterval(() => {
      setPairs((prev) =>
        prev.map((p) => ({
          ...p,
          price: +(p.price * (1 + (Math.random() - 0.5) * 0.001)).toFixed(
            p.price > 1000 ? 2 : p.price > 1 ? 4 : 8,
          ),
          change: +(p.change + (Math.random() - 0.5) * 0.05).toFixed(2),
        })),
      );
    }, 2000);
    return () => clearInterval(interval);
  }, []);
  return pairs;
}

// ── CRYPTO_DATA is used by other pages — DO NOT MODIFY ──
export const CRYPTO_DATA = [
  {
    id: "BTC",
    name: "Bitcoin",
    symbol: "BTC",
    price: 66558.0,
    change: 0.68,
    amount: 0.01,
    color: "#F7931A",
  },
  {
    id: "ETH",
    name: "Ethereum",
    symbol: "ETH",
    price: 2044.43,
    change: 0.99,
    amount: 0.25,
    color: "#627EEA",
  },
  {
    id: "SOL",
    name: "Solana",
    symbol: "SOL",
    price: 84.49,
    change: 2.14,
    amount: 1.5,
    color: "#9945FF",
  },
  {
    id: "BNB",
    name: "BNB",
    symbol: "BNB",
    price: 606.97,
    change: -0.42,
    amount: 0.5,
    color: "#F3BA2F",
  },
];
